llm:
  prompt:
    template: |
      Please perform an objective factual analysis of the following user comment and return the result strictly in JSON format as shown below:
      
      {
        "type": "opinion|fact|misinformation",
        "confidence": number between 0 and 1,
        "facts": ["fact 1", "fact 2"],
        "trustScore": number between 0 and 1
      }

      Platform: %s
      Comment: %s
