llm:
  prompt:
    template: |-
      Please perform an objective factual analysis of the following user comment...
      Platform: %s
      Comment: %s

openai:
  api-url: https://api.openai.com/v1/chat/completions
  api-key: ${OPENAI_API_KEY}
  model: gpt-4
  temperature: 0.0

deepseek:
  api-url: https://api.deepseek.com/chat/completions
  api-key: ${DEEPSEEK_API_KEY:}
  model: deepseek-chat
  temperature: 0.0
