package com.echofilter.commons.enums;

public enum ErrorCode {
    BAD_REQUEST, VALIDATION_FAILED, NOT_FOUND, CONFLICT,
    LLM_UNAUTHORIZED, LLM_RATE_LIMITED, LLM_TIMEOUT, LLM_BAD_RESPONSE, LLM_UNREACHABLE, LLM_ERROR,
    CONFIG_MISSING, STRATEGY_NOT_FOUND, SERVICE_UNAVAILABLE
}
